query ArticleBySlug ($slug: ID = "ثبتنام-اربعین-1402-در-سامانه-سماح-فردا-آغ") {
  post(idType: SLUG, id: $slug) {
    ...Post
    
    categories {
      nodes {
        name
        slug
        uri
      }
    }
    tags {
      nodes {
        name
        uri
        posts {
          nodes {
						...Post
						categories {
							nodes {
								name
								slug
								uri
							}
						}
          }
        }
      }
    } 
  }
}